##################################################################
#
#	Makefile for IMU using gcc on Linux. 
#
#
#	Modified	by	Reason
# 	--------	--	------
#	25-Feb-22       CBL     Original
#
#
######################################################################
# Machine specific stuff
#
#
LIBRARY = libIMUData.a 
#
# Compile time resolution.
#
INCLUDE = -I$(DRIVE)/common/utility 
LIBS = 

# Rules to make the object files depend on the sources.
SRC     = 
SRCCPP  = IMUData.cpp
SRCS    = $(SRC) $(SRCCPP)

HEADERS = IMUData.hh

libIMUData.a: IMUData.cpp IMUData.hh
	ar -r libIMUData.a IMUData.o

# When we build all, what do we build?
all:      $(TARGET) libIMUData.a

include $(DRIVE)/common/makefiles/makefile.inc


#dependencies
include make.depend 
# DO NOT DELETE
