##################################################################
#
#	Makefile for NMEALIB using gcc on Linux. 
#
#
#	Modified	by	Reason
# 	--------	--	------
#	24-Feb-22       CBL     Original
#
######################################################################
# Machine specific stuff
#
#
LIBRARY = libNMEA.a
#
# Compile time resolution.
#
INCLUDE = -I$(DRIVE)/common/utility 

#
LIBS = 

# Rules to make the object files depend on the sources.
SRC     = serial.c
SRCCPP  = NMEA_GPS.cpp 
SRCS    = $(SRC) $(SRCCPP)

HEADERS = NMEA_GPS.hh serial.h

# When we build all, what do we build?
all:      $(LIBRARY)

include $(DRIVE)/common/makefiles/makefile.inc


#dependencies
include make.depend 
# DO NOT DELETE
